#set text(lang: "en")
#outline()
#set heading(numbering: "1.")
#heading(level: 1)[Schedule] #label("org0000003")
#heading(level: 2)[Call Trillian for a date on New Years Eve.] #label("org0000000")
DEADLINE: #datetime(year: 2004, month: 2, day: 29).display()
