# Example code taken from https://github.com/Sematre/typst-letter-pro
# and converted to org-mode.

#+TYPST: #import "@preview/letter-pro:2.1.0": letter-simple
#+LANGUAGE: de
#+TITLE: Einspruch gegen den ESt-Bescheid

# Disable TOC, since it will be put at the top of the docmeent which
# doesnt work with the letter package.
#+OPTIONS: toc:nil

#+BEGIN_EXPORT typst
#show: letter-simple.with(
  sender: (
    name: "Anja Ahlsen",
    address: "Deutschherrenufer 28, 60528 Frankfurt",
    extra: [
      Telefon: #link("tel:+4915228817386")[+49 152 28817386]\
      E-Mail: #link("mailto:aahlsen@example.com")[aahlsen\@example.com]\
    ],
  ),
  annotations: [Einschreiben - Rückschein],
  recipient: [
    Finanzamt Frankfurt\
    Einkommenssteuerstelle\
    Gutleutstraße 5\
    60329 Frankfurt
  ],
  reference-signs: (
    ([Steuernummer], [333/24692/5775]),
  ),
  date: "12. November 2014",
  subject: "Einspruch gegen den ESt-Bescheid",
)
#+END_EXPORT

#+TOC: headlines 2
#+TOC: listings
#+TOC: tables

Sehr geehrte Damen und Herren,

die von mir bei den Werbekosten geltend gemachte Abschreibung für den im
vergangenen Jahr angeschafften Fotokopierer wurde von Ihnen nicht berücksichtigt.
Der Fotokopierer steht in meinem Büro und wird von mir ausschließlich zu beruflichen
Zwecken verwendet.

Ich lege deshalb Einspruch gegen den oben genannten Einkommensteuerbescheid ein
und bitte Sie, die Abschreibung anzuerkennen.

Anbei erhalten Sie eine Kopie der Rechnung des Gerätes.

Mit freundlichen Grüßen
#+TYPST: #v(1cm)
Anja Ahlsen

#+TYPST: #v(1fr)
*Anlagen:*
- Rechnung
