name: Nix Tests

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v29
      - name: Check Formatting
        run: |
          nix run nixpkgs#alejandra -- -c ./**/*.nix
